### ISSUE TITLE
allow skipping of frames where PROPKA fails

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/propkatraj#10]
If PROPKA fails for mysterious reasons then we want to have the option to move on and skip frames.

# requirements

- keyword argument that allows ignoring failing frames (`skip_failing = True`)
- use `try/except` to skip
- log frames that fail
- log error message at end if any frames were skipped and summarize the percentage of skipped frames

# design notes
Put a `try/except` around https://github.com/Becksteinlab/propkatraj/blob/master/propkatraj/propkatraj.py#L74 together with the logging.

- If `skip_failing = False` then raise the exception.
- If `skip_failing = True` then log error and continue 

Something like
```python
try:
        mol = pk.single(pstream, optargs=['--quiet'])
except IndexError as err:
        if not skip_failing:
            raise
        else:
            # log ...
            # continue the loop at the next frame, not sure if this
            # is working....
            continue
finally:
       pstream.close(force=True) # deallocate
```

(`IndexError` is the PROPKA error that @rsexton2  encounters.)

**Comment by orbeckst** [comment]
@rsexton2 please attach a zip file with structure and trajectory that fail together with the code you used for testing. Thanks!

**Comment by rsexton2** [comment]
Script used where failing frame is isolated (ts = 1414ns).
```python
import MDAnalysis as mda
import propkatraj

traj = 'test_traj.xtc'
topology = 'test_top.gro'
u = mda.Universe(topology, traj)

pkas = propkatraj.get_propka(u, sel='protein', skip_failure=True, start=10, stop=19)
```

**Comment by rsexton2** [comment]
Zip file containing the topology and trajectory where propka fails.

[test_traj_top.zip](https://github.com/Becksteinlab/propkatraj/files/1450555/test_traj_top.zip)
