### ISSUE TITLE
Error running propkatraj as in tutorial

### ISSUE THREAD

**Issue by nehadelsalamouny** [Becksteinlab/propkatraj#18]
I am following the Jupyter notebook tutorial (docs/propkatraj-example.ipynb) and when I type 
pkas = propkatraj.get_propka(u) I get the following error. I am not sure what the problem is. Many thanks

>>> pkas = propkatraj.get_propka(u)
    1/98 t=       1.000 ps  [  1.0%]/Users/nehade/anaconda3/lib/python3.5/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'altLocs' Using default value of ' '
  "".format(attrname, default))
/Users/nehade/anaconda3/lib/python3.5/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'icodes' Using default value of ' '
  "".format(attrname, default))
/Users/nehade/anaconda3/lib/python3.5/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'occupancies' Using default value of '1.0'
  "".format(attrname, default))
/Users/nehade/anaconda3/lib/python3.5/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'tempfactors' Using default value of '0.0'
  "".format(attrname, default))

**Traceback (most recent call last):**
  File "/Users/nehade/.local/lib/python3.5/site-packages/PROPKA-3.1-py3.5.egg/propka/lib.py", line 37, in open_file_for_reading
TypeError: invalid file: <NamedStream(<_io.StringIO object at 0x110245c18>, /Users/nehade/anaconda3/lib/python3.5/site-packages/MDAnalysisTests/data/current.pdb)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nehade/.local/lib/python3.5/site-packages/propkatraj/propkatraj.py", line 82, in get_propka
    mol = pk.single(pstream, optargs=['--quiet'])
  File "/Users/nehade/.local/lib/python3.5/site-packages/PROPKA-3.1-py3.5.egg/propka/run.py", line 30, in single
  File "/Users/nehade/.local/lib/python3.5/site-packages/PROPKA-3.1-py3.5.egg/propka/molecular_container.py", line 41, in __init__
  File "/Users/nehade/.local/lib/python3.5/site-packages/PROPKA-3.1-py3.5.egg/propka/pdb.py", line 40, in read_pdb
    printed but the debugger's state is not changed.
  File "/Users/nehade/.local/lib/python3.5/site-packages/PROPKA-3.1-py3.5.egg/propka/pdb.py", line 91, in get_atom_lines_from_pdb
    def find_function(funcname, filename):
  File "/Users/nehade/.local/lib/python3.5/site-packages/PROPKA-3.1-py3.5.egg/propka/lib.py", line 39, in open_file_for_reading
OSError: Cannot find file /Users/nehade/anaconda3/lib/python3.5/site-packages/MDAnalysisTests/data/current.pdb
>>>

**Comment by orbeckst** [comment]
I tried this locally (Python 3.6 on macOS 10.12 with MDAnalysis 0.19.2) and this works as expected. Did you install propka with
```
pip install propka
```
? 

Check that your `propka/lib.py` contains the following code https://github.com/jensengroup/propka-3.1/blob/91925bb92092d3b180a9c086e81822a3fdec6939/propka/lib.py#L16-L41 (click on the link to see the code). Your installed file is `/Users/nehade/.local/lib/python3.5/site-packages/PROPKA-3.1-py3.5.egg/propka/lib.py`. If you installed propka from PyPi then this should be in there. This is the code that makes it work with propkatraj.

**Comment by nehadelsalamouny** [comment]
I installed propka using the instructions in: https://github.com/jensengroup/propka-3.1
I checked my folders:
in /Users/nehade/.local/lib/python3.5/site-packages/ 
PROPKA-3.1-py3.5.egg is a file not a folder. And so I don't have PROPKA-3.1-py3.5.egg/propka/lib.py
I removed propka then reinstalled it using PyPi and it worked!
Many thanks
