### ISSUE TITLE
ProgressMeter removal in MDAnalysis 2.0

### ISSUE THREAD

**Issue by IAlibay** [Becksteinlab/propkatraj#19]
As the progressmeter has now been replaced by the progressbar, the following will fail from 2.0 onwards:

https://github.com/Becksteinlab/propkatraj/blob/2abd91fca33a5e980a2b8d8c6e18a2d192fda2c3/propkatraj/propkatraj.py#L61

I would be interested in attempting to refactor the code to use AnalysisBase instead if there is any interest in doing so.

**Comment by orbeckst** [comment]
YES, PLEASE! This might make for a decent example for code outside MDAnalysis.analysis can leverage AnalysisBase.

Also note that propka is now 3.2 so there might have been some API breaks. But the good news is that propka is now properly versioned and maintained.

**Comment by IAlibay** [comment]
Closed with #26
