### ISSUE TITLE
remove MDSynthesis dependency

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/propkatraj#2]
The `propkatraj.py` script uses MDSynthesis. Should we retain this dependency or make it more bare-bones?

@dotsdl , have you got an opinion?

**Comment by dotsdl** [comment]
@orbeckst in general we should shy away from MDS as a dependency, and I think this can almost certainly be written to get away with that. This "library" started as a code dump, and writing things in terms of MDS objects made the initial implementation easier. Hacking on it now.

**Comment by orbeckst** [comment]
Ok, it seems easy enough to pass in a universe. ... basically we could use the new analysis class and be done. (AnalysisFromFunction() or similar decorator magic might work.)

Just returning the dataframe is also cleaner than saving them somewhere in a cryptic datreant leaf (which I haven't explicitly documented...).

If you tell me what you want to do or just push a PR I can also hack on it, e.g., work on docs or example notebook.

**Comment by dotsdl** [comment]
Removed all usage of Sims in 260c305216eb07ddda776f4b0a8dc912b108081b. The `get_propka` function now takes a `Universe` and returns a `DataFrame`.

**Comment by orbeckst** [comment]
Nice. Thank you. 

--
Oliver Beckstein
email: orbeckst@gmail.com
