### ISSUE TITLE
Passing an index array fails

### ISSUE THREAD

**Issue by IAlibay** [Becksteinlab/propkatraj#22]
The current code _should_ support passing an array index instead of a string selection.

However the following will cause a `TypeError`.

```python
```

The reason for this is here:
https://github.com/Becksteinlab/propkatraj/blob/2abd91fca33a5e980a2b8d8c6e18a2d192fda2c3/propkatraj/propkatraj.py#L53

The latter should be np.ndarray not np.array.

Suggestion: the fix is quite trivial so it's not an issue, but I would suggest relying on users passing atomgroups instead of universes, with the default selection string being `None` (if a selection string is even needed). That way the responsibility is on users to pass the right thing?

**Comment by orbeckst** [comment]
I don’t remember why we even had that in here... let’s do the formal fix in 8878990 and then decide if this should be changed.

**Comment by IAlibay** [comment]
Fixed in #21
