### ISSUE TITLE
get_propka will fail with file generated via `fetch_mmtf`

### ISSUE THREAD

**Issue by IAlibay** [Becksteinlab/propkatraj#23]
As the the "filename" for the PDB stream relies on `universe.filename` universes without filenames set, e.g. when using `fetch_mmtf` will cause `get_propka` to fail.

Code to reproduce behaviour:

```python
import MDAnalysis as mda
import propkatraj

u = mda.fetch_mmtf('4LYI')

pkatraj = propkatraj.get_propka(u)
```

Note; this might not need fixing, in the AnalysisBase update I would like to switch to using `os.path.curdir`.

**Comment by orbeckst** [comment]
propkatrj predates fetch_mmtf as far as I remember... a quick hack might be to just manually add `trajectory.filename`. However, if this gets fixed in rewrite then all the better.
