### ISSUE TITLE
standard setuptools installation 

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/propkatraj#3]
It should be possible to install this script with its dependencies in a standard Pythonic manner.

Current dependencies
* numpy
* pandas
* MDAnalysis
* MDSynthesis
* [PROPKA 3.1](https://github.com/jensengroup/propka-3.1) — not on PyPi, no releases on GitHub.

**Comment by orbeckst** [comment]
This will probably require that jensengroup/propka-3.1#16 gets resolved.

**Comment by dotsdl** [comment]
This package is now pip installable; requires propka but that must be installed separately since it's not available in PyPI.
