### ISSUE TITLE
remove deprecated functionality

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/propkatraj#30]
For a 2.0 release, remove deprecated stuff
- [ ] get_propka
- [ ] Python ≤ 3.5 (six, future etc can go)

Bump dependencies
- [ ] MDAnalysis ≥ 1.0
- [ ] propka ≥ 3.2
- [ ] Python ≥ 3.6 (in setup.py and remove jobs from Travis CI)

**Comment by IAlibay** [comment]
Fixed via #34
