### ISSUE TITLE
2.0.0 release

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/propkatraj#37]
With #36, the `get_propka` function is removed. Per the deprecation warning, this means a release of 2.0.0 is needed. 

## Release checklist

- [x] addressed all issues for [2.0.0 milestone](https://github.com/Becksteinlab/propkatraj/milestone/1)
- [x] updated release (PR #50 )
- [x] tagged  as `2.0.0`
- [x] tested package
- [x] created new [release](https://github.com/Becksteinlab/propkatraj/releases) on GitHub
- [x] upload to test.pypi.org (create package on test.pypi.org first, add @IAlibay and @orbeckst as admins)
- [x] test the test.pypi package
- [x] upload pypi package

**Comment by orbeckst** [comment]
See https://github.com/Becksteinlab/propkatraj/issues/20#issuecomment-1429983829 for decision to release a version that restricts compatibility to earlier version of PROPKA.

**Comment by orbeckst** [comment]
I added a generic release checklist.

@ianmkenney can you please be in charge to create the package on https://test.pypi.org/ for an initial package test. It's a 2.0.0 so let's get the package right first time and not have to do 2.0.1 on pypi immediately...

@ianmkenney  we currently do not have an automated deployment workflow so we need to do test.pypi and pypi manually. @IAlibay, have you repackaged your deployment workflows as actions already?

**Comment by IAlibay** [comment]
> @IAlibay, have you repackaged your deployment workflows as actions already?

Unfortunately it's not finished yet, probably would aim for the 2.1 release. To be honest, as long as it uploads to testpypi we shouldn't have too much trouble with packaging here.

Note: we should try to uplaod wheels too if we can.

**Comment by ianmkenney** [comment]
@IAlibay @orbeckst what are your test pypi usernames?

**Comment by IAlibay** [comment]
IAlibay I'm a simple person :P

**Comment by orbeckst** [comment]
Oliver.Beckstein IIRCAm 2/15/23 um 12:37 schrieb Irfan Alibay ***@***.***>:﻿
IAlibay I'm a simple person :P

**Comment by ianmkenney** [comment]
@orbeckst @IAlibay should be done

**Comment by orbeckst** [comment]
Then go ahead and close the issue!
