### ISSUE TITLE
Fix coveragerc to not try to cover things that we don't need to check

### ISSUE THREAD

**Issue by IAlibay** [Becksteinlab/propkatraj#39]
Our coverage is artificially low, we can fix coveragerc to exclude anything that isn't under  (e.g. everything that isn't in `propkatraj.py` or `propkatraj/tests`.

We can also quickly add an nbval test (alongside the standard CI test action) to run the examples through - although that's not a coverage thing.

**Comment by orbeckst** [comment]
PR #46 addressed everything.
