### ISSUE TITLE
review current repo for 0.1.0 release

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/propkatraj#4]
@dotsdl and @azjajo – please have a look at the repo and let me know if anything needs to be changed/added. (PRs or direct commits are welcome).

I tested the installation instructions in a virtual env and everything works with MDA 0.16.0 and current MDSynthesis as well as PROPKA 3.1. master.

If you are happy I cut a 0.1.0 release (and possibly add citation information).

**Comment by orbeckst** [comment]
@dotsdl and @azjajo : yay/nay/need more time to look at?

**Comment by ghost** [comment]
Well done. My vote is yay!

**Comment by dotsdl** [comment]
@orbeckst reviewing now. Might do a lot of cutting.

**Comment by orbeckst** [comment]
See #2 ...

**Comment by dotsdl** [comment]
@orbeckst done; I've also updated the notebook so it reflects current functionality.

**Comment by orbeckst** [comment]
Great!  Thank you. 

--
Oliver Beckstein
email: orbeckst@gmail.com
