### ISSUE TITLE
add new pypi maintainers

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/propkatraj#41]
# invitation sent
- [x] add @ianmkenney as maintainer for PyPi
- [x] add @IAlibay as maintainer

# invitation accepted
- [x] @ianmkenney 
- [x] @IAlibay

**Comment by orbeckst** [comment]
I invited you both @ianmkenney and @IAlibay . Once you confirm that you accepted (or declined) the invitation I'll close the issue.

**Comment by IAlibay** [comment]
should be done thanks!
