### ISSUE TITLE
Fix license

### ISSUE THREAD

**Issue by IAlibay** [Becksteinlab/propkatraj#48]
Says GPLv3 in some places, says GPLv2 in others. Need to pick one and choose.

**Comment by ianmkenney** [comment]
I see mostly v2 or later, so I say we move to v3 or later

**Comment by IAlibay** [comment]
where does it say gplv3? if it's just one place then we can probably safely assume it can be gplv2+ tbh

**Comment by ianmkenney** [comment]
closed with PR #51
