### ISSUE TITLE
api doc formatting of argument lists messed up

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/propkatraj#55]
In https://becksteinlab.github.io/propkatraj/api.html , the argument name and type are not separated.

**Comment by IAlibay** [comment]
That's rather odd, the docstring seems well formed.

**Comment by IAlibay** [comment]
I got it I think, we're missing a sphinx extension

**Comment by orbeckst** [comment]
Makes sense, because when I build locally, it looks fine.

**Comment by orbeckst** [comment]
... but I built in my mda dev env which probably has everything needed.
