### ISSUE TITLE
Make python support 3.9+

### ISSUE THREAD

**Issue by IAlibay** [Becksteinlab/propkatraj#61]
Now that MDA has dropped 3.8, we should also move ahead with removing 3.8 support.

**Comment by orbeckst** [comment]
This will require at least a minor release.

**Comment by IAlibay** [comment]
So the deeper issue that needs addressing here is that we have the one matrix for both latest and develop - ideally we should have the python ranges on develop just skip if the python version isn't supported.

**Comment by orbeckst** [comment]
skipping to 3.10
