### ISSUE TITLE
AttributeError: module 'propkatraj' has no attribute 'get_propka'

### ISSUE THREAD

**Issue by evelyne-deplazes** [Becksteinlab/propkatraj#64]
Hi 

I am having issues running propkatraj and I think it's related to my local propkatraj or Propka installation because the error I get is 

AttributeError: module 'propkatraj' has no attribute 'get_propka'

(I get no error about the module not being found)

I have MDAnalysis 2.5 installed (on a MacOS 10.15) and that works fine. I have install propka and propkatraj using 

pip install propka==3.1  
pip install propkatraj 

No error messages during the installation

I tried a very stripped-back test script (see attached) but I can't even call the function help(propkatraj.get_propka)

Any help would be much appreciated.

thanks from Australia 
Evelyne 

I came across this older issue 
https://github.com/Becksteinlab/propkatraj/issues/18 

I checked the lib.py in /Users/evelyne/opt/anaconda3/lib/python3.9/site-packages/propka/lib.py and as far as I can tell the required code for the function open_file_for_reading is there 
[pka_test.txt](https://github.com/Becksteinlab/propkatraj/files/11765799/pka_test.txt)

**Comment by IAlibay** [comment]
Hi @evelyne-deplazes,

The `get_propka` method was replaced in the last release of propkatraj. Instead you must now use the `PropakTraj` class. We have some example usage here which should help translate any code you currently rely on: https://becksteinlab.github.io/propkatraj/usage/examples.html

**Comment by orbeckst** [comment]
I hope that using the new API solved your problem. I am going to close but please feel free to ask again/reopen if necessary.
