### ISSUE TITLE
Tests fail for MDAKit registry check

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/propkatraj#72]
Tests fail for MDAKit registry check https://github.com/MDAnalysis/MDAKits/issues/153 and https://github.com/MDAnalysis/MDAKits/issues/152

(Need to check what is actually going wrong and what needs fixing.)

**Comment by orbeckst** [comment]
Not sure where to look to find out what's actually wrong – see https://github.com/MDAnalysis/MDAKits/issues/152#issuecomment-2212497857

**Comment by IAlibay** [comment]
@orbeckst the issue is with the `fetch_mmtf` command - apologies I ran out of time last night to raise relevant details. Working on a solution.
